api = "0.7"

[buildpack]
  description = "A buildpack for starting a passenger server for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/passenger"
  id = "paketo-buildpacks/passenger"
  keywords = ["ruby", "passenger"]
  name = "Paketo Buildpack for Passenger"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/passenger/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:366482f2493f776687d0d67ab757d8883b9d879c360e87f06930ba10b0a120b5"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_jammy_366482f2.tgz"
    version = "8.22.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:858843d6244a68eec1a6a45f822c6bae966a863430633ff2259483b888b8adfb"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_jammy_858843d6.tgz"
    version = "8.22.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:7ac1c7ece2ae27ccebd382f1c707cd1cd0d96c12be3b848a34fddafa29941929"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_noble_7ac1c7ec.tgz"
    version = "8.22.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:af23042ee3e270f3f38ae7e70ddbe6b72a6b21d5ade4df251a5e2e56211d87d3"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_noble_af23042e.tgz"
    version = "8.22.0"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:fddf9b435774e4b55dac11789f3dea7f93f482ee365d382aa6757e3fd1fe4b2c"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_resolute_fddf9b43.tgz"
    version = "8.22.0"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:d0171f27d124f1d555545dc58a8562b83269561eb410f2f9d3a846856b3d7baa"
    cpe = "cpe:2.3:a:haxx:curl:8.22.0:*:*:*:*:*:*:*"
    id = "curl"
    licenses = ["curl"]
    name = "cURL"
    os = "linux"
    purl = "pkg:generic/curl@8.22.0?checksum=d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1&download_url=https://curl.se/download/curl-8.22.0.tar.gz"
    source = "https://curl.se/download/curl-8.22.0.tar.gz"
    source-checksum = "sha256:d54dd598bf05927a726deb38df31c6a255ba83ff1de57c5d1464dac3ed8f44a1"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/curl/curl_8.22.0_linux_resolute_d0171f27.tgz"
    version = "8.22.0"

  [[metadata.dependency-constraints]]
    constraint = "8.*"
    id = "curl"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[stacks]]
  id = "io.buildpacks.stacks.resolute"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
